<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_ID OrganisasiPerusahaan</name>
   <tag></tag>
   <elementGuidId>a335ff8c-7103-4d8e-be4a-3dacfe5ed544</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/main/main/div[2]/div/form/div/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>label.black</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>c3687a0b-2f79-4573-942a-8da5d5528d89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>black</value>
      <webElementGuid>af830590-4ec6-412c-b336-669babe4d7c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>id</value>
      <webElementGuid>50a8e45b-f788-4f9d-b426-3aa360cfb176</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ID Organisasi/Perusahaan</value>
      <webElementGuid>75a306a6-adfe-409f-b209-4116674aa837</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/main[1]/main[@class=&quot;authentication&quot;]/div[@class=&quot;form-container&quot;]/div[@class=&quot;card&quot;]/form[1]/div[@class=&quot;form-control&quot;]/label[@class=&quot;black&quot;]</value>
      <webElementGuid>bf3c3db2-4ba2-4aea-ad4c-efb505d77363</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/main/main/div[2]/div/form/div/label</value>
      <webElementGuid>8a5f5bc5-d04f-43e3-8797-ff4fda1abaf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sistem informasi kesehatan terpadu untuk pelayanan medis'])[1]/following::label[1]</value>
      <webElementGuid>9b19784a-4077-4757-95ae-9d0db916702c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label</value>
      <webElementGuid>09868d65-4a57-4f1d-a64e-08a1307d17a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'ID Organisasi/Perusahaan' or . = 'ID Organisasi/Perusahaan')]</value>
      <webElementGuid>506c71cd-f314-4bbd-b95c-3963574db7b3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
